---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    name: voting-app-service
    app: facebook
spec:
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    name: voting-app
    app: facebook